### ISSUE TITLE
Trying to change anything in config crashes the app

### ISSUE THREAD

**Issue by nnbveh** [konsumer/rm8#6]
When i try to change something on the first page of the config(whe you choose audio etc) it just crashes the app:

thread 'main' panicked at 'not yet implemented', src\m8.rs:90:26

I'm running it on windows 11

**Comment by konsumer** [comment]
Yeh, there is a few options that are not implemented around messing with the audio, specifically. It's a hack to get it working cross-platform in the first place (it's actually a very complicated problem.) I will close this, as the `not yet implemented` are the documentation for that.
